
const publications=window.PUBLICATIONS,gallery=window.GALLERY;
const escapeHtml=(value='')=>value.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const doi=item=>item.doi?'https://doi.org/'+item.doi:'#';
let galleryIndex=0,visible=16,filtered=[...publications];
function showGallery(index){galleryIndex=(index+gallery.length)%gallery.length;const item=gallery[galleryIndex],paper=publications.find(entry=>entry.key===item.publicationKey),src='scientific-gallery/'+encodeURIComponent(item.file);document.querySelector('#gallery-image').src=src;document.querySelector('#gallery-image').alt=item.title;document.querySelector('#gallery-stage').setAttribute('aria-label','Open '+item.title+' in full screen');document.querySelector('#gallery-title').textContent=item.title;document.querySelector('#gallery-count').textContent=String(galleryIndex+1).padStart(2,'0')+' / '+gallery.length;document.querySelector('#gallery-full').src=src;document.querySelector('#gallery-full').alt=item.title;const details=document.querySelector('#gallery-publication');details.hidden=!paper;if(paper){document.querySelector('#gallery-paper-link').textContent=paper.title;document.querySelector('#gallery-paper-link').href=doi(paper);document.querySelector('#gallery-paper-authors').textContent=paper.authors;document.querySelector('#gallery-paper-meta').innerHTML='<span>'+escapeHtml(paper.journal)+'</span><span>'+paper.year+'</span>'+(paper.impact?'<span>IF '+paper.impact+'</span>':'')+'<a href="'+doi(paper)+'">View paper ↗</a>';}document.querySelectorAll('[data-gallery]').forEach((button,i)=>button.classList.toggle('active',i===galleryIndex));}
document.querySelector('#gallery-prev').addEventListener('click',()=>showGallery(galleryIndex-1));document.querySelector('#gallery-next').addEventListener('click',()=>showGallery(galleryIndex+1));document.querySelector('#gallery-stage-prev').addEventListener('click',()=>showGallery(galleryIndex-1));document.querySelector('#gallery-stage-next').addEventListener('click',()=>showGallery(galleryIndex+1));document.querySelectorAll('[data-gallery]').forEach(button=>button.addEventListener('click',()=>showGallery(Number(button.dataset.gallery))));const lightbox=document.querySelector('#gallery-lightbox');document.querySelector('#gallery-stage').addEventListener('click',()=>{lightbox.hidden=false;});document.querySelector('#gallery-close').addEventListener('click',()=>{lightbox.hidden=true;});lightbox.addEventListener('click',event=>{if(event.target===lightbox)lightbox.hidden=true;});document.addEventListener('keydown',event=>{if(event.key==='Escape')lightbox.hidden=true;});
function row(item,index){return '<article class="publication-row"><a class="record-cover" href="'+doi(item)+'" aria-label="View '+escapeHtml(item.title)+'"><img src="publication-covers/'+encodeURIComponent(item.cover)+'" alt="Cover or graphical abstract for '+escapeHtml(item.title)+'" width="240" height="150" loading="lazy"></a><span class="record-number">'+String(index+1).padStart(3,'0')+'</span><div class="record-main"><h3><a href="'+doi(item)+'">'+escapeHtml(item.title)+'</a></h3><p>'+escapeHtml(item.authors)+'</p><div><span>'+escapeHtml(item.journal)+'</span><span>'+item.year+'</span>'+(item.impact?'<span>IF '+item.impact+'</span>':'')+'</div></div></article>'}
function render(){const list=document.querySelector('#publication-list');list.innerHTML=filtered.slice(0,visible).map(row).join('')||'<p class="empty-state">No publications match this search.</p>';document.querySelector('#result-count').textContent=filtered.length+' results';const more=document.querySelector('#load-more');more.hidden=visible>=filtered.length;more.innerHTML='Load more <span>('+(filtered.length-visible)+' remaining)</span>';}
function filter(){const query=document.querySelector('#publication-search').value.trim().toLowerCase(),year=document.querySelector('#publication-year').value;filtered=publications.filter(item=>(year==='All years'||String(item.year)===year)&&(!query||(item.title+' '+item.authors+' '+item.journal).toLowerCase().includes(query)));visible=16;render();}
document.querySelector('#publication-search').addEventListener('input',filter);document.querySelector('#publication-year').addEventListener('change',filter);document.querySelector('#load-more').addEventListener('click',()=>{visible+=24;render();});
