
const publications=window.PUBLICATIONS,spotlight=window.SPOTLIGHT;
const escapeHtml=(value='')=>value.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const doi=item=>item.doi?'https://doi.org/'+item.doi:'#';
let spotlightIndex=0,visible=16,filtered=[...publications];
function showSpotlight(index){spotlightIndex=(index+spotlight.length)%spotlight.length;const item=spotlight[spotlightIndex];document.querySelector('#spotlight-image').src='publication-covers/'+encodeURIComponent(item.cover);document.querySelector('#spotlight-image').alt='Cover or graphical abstract for '+item.title;document.querySelector('#spotlight-meta').innerHTML='<span>'+item.year+'</span><span>'+escapeHtml(item.journal)+'</span>'+(item.impact?'<span>IF '+item.impact+'</span>':'');document.querySelector('#spotlight-title').textContent=item.title;document.querySelector('#spotlight-authors').textContent=item.authors;document.querySelector('#spotlight-link').href=doi(item);document.querySelectorAll('[data-spotlight]').forEach((button,i)=>button.classList.toggle('active',i===spotlightIndex));}
document.querySelector('#spotlight-prev').addEventListener('click',()=>showSpotlight(spotlightIndex-1));document.querySelector('#spotlight-next').addEventListener('click',()=>showSpotlight(spotlightIndex+1));document.querySelectorAll('[data-spotlight]').forEach(button=>button.addEventListener('click',()=>showSpotlight(Number(button.dataset.spotlight))));setInterval(()=>showSpotlight(spotlightIndex+1),7000);
function row(item,index){return '<article class="publication-row"><a class="record-cover" href="'+doi(item)+'" aria-label="View '+escapeHtml(item.title)+'"><img src="publication-covers/'+encodeURIComponent(item.cover)+'" alt="Cover or graphical abstract for '+escapeHtml(item.title)+'" width="240" height="150" loading="lazy"></a><span class="record-number">'+String(index+1).padStart(3,'0')+'</span><div class="record-main"><h3><a href="'+doi(item)+'">'+escapeHtml(item.title)+'</a></h3><p>'+escapeHtml(item.authors)+'</p><div><span>'+escapeHtml(item.journal)+'</span><span>'+item.year+'</span>'+(item.impact?'<span>IF '+item.impact+'</span>':'')+'</div></div></article>'}
function render(){const list=document.querySelector('#publication-list');list.innerHTML=filtered.slice(0,visible).map(row).join('')||'<p class="empty-state">No publications match this search.</p>';document.querySelector('#result-count').textContent=filtered.length+' results';const more=document.querySelector('#load-more');more.hidden=visible>=filtered.length;more.innerHTML='Load more <span>('+(filtered.length-visible)+' remaining)</span>';}
function filter(){const query=document.querySelector('#publication-search').value.trim().toLowerCase(),year=document.querySelector('#publication-year').value;filtered=publications.filter(item=>(year==='All years'||String(item.year)===year)&&(!query||(item.title+' '+item.authors+' '+item.journal).toLowerCase().includes(query)));visible=16;render();}
document.querySelector('#publication-search').addEventListener('input',filter);document.querySelector('#publication-year').addEventListener('change',filter);document.querySelector('#load-more').addEventListener('click',()=>{visible+=24;render();});
