
const publications=window.PUBLICATIONS,gallery=window.GALLERY;
const escapeHtml=(value='')=>value.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const doi=item=>item.doi?'https://doi.org/'+item.doi:'#';
let galleryIndex=0,visible=16,filtered=[...publications];
function showGallery(index){galleryIndex=(index+gallery.length)%gallery.length;const item=gallery[galleryIndex],paper=publications.find(entry=>entry.key===item.publicationKey),src='scientific-gallery/'+encodeURIComponent(item.file),image=document.querySelector('#gallery-image');image.src=src;image.alt=paper?paper.title:'Scientific illustration';image.animate([{opacity:.12,transform:'scale(.995)'},{opacity:1,transform:'scale(1)'}],{duration:650,easing:'ease'});document.querySelector('#gallery-overlay-meta').textContent=paper?paper.journal+' · '+paper.year:'';const title=document.querySelector('#gallery-overlay-title');title.textContent=paper?paper.title:'';title.href=paper?doi(paper):'#';document.querySelectorAll('[data-gallery]').forEach((button,i)=>button.classList.toggle('active',i===galleryIndex));}
document.querySelector('#gallery-prev').addEventListener('click',()=>showGallery(galleryIndex-1));document.querySelector('#gallery-next').addEventListener('click',()=>showGallery(galleryIndex+1));document.querySelector('#gallery-stage-prev').addEventListener('click',()=>showGallery(galleryIndex-1));document.querySelector('#gallery-stage-next').addEventListener('click',()=>showGallery(galleryIndex+1));document.querySelectorAll('[data-gallery]').forEach(button=>button.addEventListener('click',()=>showGallery(Number(button.dataset.gallery))));setInterval(()=>{let next=galleryIndex;while(next===galleryIndex)next=Math.floor(Math.random()*gallery.length);showGallery(next);},6000);const hidePubPeerBanner=()=>document.querySelectorAll('body > *').forEach(element=>{if(element.tagName!=='MAIN'&&element.innerText&&element.innerText.includes('PubPeer comments'))element.style.setProperty('display','none','important');});hidePubPeerBanner();new MutationObserver(hidePubPeerBanner).observe(document.body,{childList:true});document.addEventListener('keydown',event=>{if(['INPUT','SELECT','TEXTAREA'].includes(event.target.tagName))return;if(event.key==='ArrowLeft')showGallery(galleryIndex-1);if(event.key==='ArrowRight')showGallery(galleryIndex+1);});
function row(item,index){return '<article class="publication-row"><a class="record-cover" href="'+doi(item)+'" aria-label="View '+escapeHtml(item.title)+'"><img src="publication-covers/'+encodeURIComponent(item.cover)+'" alt="Cover or graphical abstract for '+escapeHtml(item.title)+'" width="240" height="150" loading="lazy"></a><span class="record-number">'+String(index+1).padStart(3,'0')+'</span><div class="record-main"><h3><a href="'+doi(item)+'">'+escapeHtml(item.title)+'</a></h3><p>'+escapeHtml(item.authors)+'</p><div><span>'+escapeHtml(item.journal)+'</span><span>'+item.year+'</span>'+(item.impact?'<span>IF '+item.impact+'</span>':'')+'</div></div></article>'}
function render(){const list=document.querySelector('#publication-list');list.innerHTML=filtered.slice(0,visible).map(row).join('')||'<p class="empty-state">No publications match this search.</p>';document.querySelector('#result-count').textContent=filtered.length+' results';const more=document.querySelector('#load-more');more.hidden=visible>=filtered.length;more.innerHTML='Load more <span>('+(filtered.length-visible)+' remaining)</span>';}
function filter(){const query=document.querySelector('#publication-search').value.trim().toLowerCase(),year=document.querySelector('#publication-year').value;filtered=publications.filter(item=>(year==='All years'||String(item.year)===year)&&(!query||(item.title+' '+item.authors+' '+item.journal).toLowerCase().includes(query)));visible=16;render();}
document.querySelector('#publication-search').addEventListener('input',filter);document.querySelector('#publication-year').addEventListener('change',filter);document.querySelector('#load-more').addEventListener('click',()=>{visible+=24;render();});
